# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NowMining.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        self.Mining_continue = QtWidgets.QPushButton(Form)
        self.Mining_continue.setGeometry(QtCore.QRect(460, 540, 113, 41))
        self.Mining_continue.setObjectName("Mining_continue")
        self.hashrate_label = QtWidgets.QLabel(Form)
        self.hashrate_label.setGeometry(QtCore.QRect(220, 180, 301, 24))
        self.hashrate_label.setObjectName("hashrate_label")
        self.filepath_label = QtWidgets.QLabel(Form)
        self.filepath_label.setGeometry(QtCore.QRect(50, 400, 461, 31))
        self.filepath_label.setText("")
        self.filepath_label.setObjectName("filepath_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 50, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.address_label = QtWidgets.QLabel(Form)
        self.address_label.setGeometry(QtCore.QRect(120, 110, 461, 25))
        self.address_label.setText("")
        self.address_label.setObjectName("address_label")
        self.Mining_back = QtWidgets.QPushButton(Form)
        self.Mining_back.setGeometry(QtCore.QRect(10, 10, 113, 41))
        self.Mining_back.setObjectName("Mining_back")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.coinName_label = QtWidgets.QLabel(Form)
        self.coinName_label.setGeometry(QtCore.QRect(270, 50, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.coinName_label.setFont(font)
        self.coinName_label.setText("")
        self.coinName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coinName_label.setObjectName("coinName_label")
        self.estCoin_label = QtWidgets.QLabel(Form)
        self.estCoin_label.setGeometry(QtCore.QRect(220, 240, 301, 24))
        self.estCoin_label.setObjectName("estCoin_label")
        self.stop_pb = QtWidgets.QPushButton(Form)
        self.stop_pb.setGeometry(QtCore.QRect(100, 340, 171, 61))
        self.stop_pb.setObjectName("stop_pb")
        self.startOver_pb = QtWidgets.QPushButton(Form)
        self.startOver_pb.setGeometry(QtCore.QRect(320, 340, 171, 61))
        self.startOver_pb.setObjectName("startOver_pb")
        self.auto_cb = QtWidgets.QCheckBox(Form)
        self.auto_cb.setGeometry(QtCore.QRect(50, 430, 151, 51))
        self.auto_cb.setObjectName("auto_cb")
        self.coinName_cb = QtWidgets.QLabel(Form)
        self.coinName_cb.setGeometry(QtCore.QRect(195, 448, 61, 16))
        self.coinName_cb.setObjectName("coinName_cb")
        self.coinName_cb_2 = QtWidgets.QLabel(Form)
        self.coinName_cb_2.setGeometry(QtCore.QRect(260, 448, 191, 16))
        self.coinName_cb_2.setObjectName("coinName_cb_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Mining_continue.setText(_translate("Form", "Continue"))
        self.hashrate_label.setText(_translate("Form", "123"))
        self.label.setText(_translate("Form", "Mining"))
        self.label_4.setText(_translate("Form", "Hash Rate:"))
        self.label_5.setText(_translate("Form", "Estimated Coin:"))
        self.Mining_back.setText(_translate("Form", "Back"))
        self.label_3.setText(_translate("Form", "Address:"))
        self.estCoin_label.setText(_translate("Form", "123"))
        self.stop_pb.setText(_translate("Form", "Stop Mining"))
        self.startOver_pb.setText(_translate("Form", "Start Over"))
        self.auto_cb.setText(_translate("Form", "Automatically mine "))
        self.coinName_cb.setText(_translate("Form", "Ethereum"))
        self.coinName_cb_2.setText(_translate("Form", "next time Mr. Miner starts"))

