# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NowMining.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NowMining(object):
    def setupUi(self, NowMining):
        NowMining.setObjectName("NowMining")
        NowMining.resize(590, 600)
        NowMining.setStyleSheet("background-color:rgb(33, 33, 33);\n"
"\n"
"")
        self.coinName_label = QtWidgets.QLabel(NowMining)
        self.coinName_label.setGeometry(QtCore.QRect(260, 80, 251, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coinName_label.sizePolicy().hasHeightForWidth())
        self.coinName_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.coinName_label.setFont(font)
        self.coinName_label.setStyleSheet("\n"
"color:rgb(255, 255, 255)\n"
"")
        self.coinName_label.setText("")
        self.coinName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coinName_label.setObjectName("coinName_label")
        self.label = QtWidgets.QLabel(NowMining)
        self.label.setGeometry(QtCore.QRect(110, 80, 121, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.estCoin_label = QtWidgets.QLabel(NowMining)
        self.estCoin_label.setGeometry(QtCore.QRect(320, 320, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estCoin_label.sizePolicy().hasHeightForWidth())
        self.estCoin_label.setSizePolicy(sizePolicy)
        self.estCoin_label.setStyleSheet("\n"
"color:rgb(255, 255, 255)\n"
"")
        self.estCoin_label.setObjectName("estCoin_label")
        self.label_5 = QtWidgets.QLabel(NowMining)
        self.label_5.setGeometry(QtCore.QRect(60, 310, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.coinName_cb_2 = QtWidgets.QLabel(NowMining)
        self.coinName_cb_2.setGeometry(QtCore.QRect(280, 528, 191, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coinName_cb_2.sizePolicy().hasHeightForWidth())
        self.coinName_cb_2.setSizePolicy(sizePolicy)
        self.coinName_cb_2.setObjectName("coinName_cb_2")
        self.Mining_back = QtWidgets.QPushButton(NowMining)
        self.Mining_back.setGeometry(QtCore.QRect(20, 10, 113, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mining_back.sizePolicy().hasHeightForWidth())
        self.Mining_back.setSizePolicy(sizePolicy)
        self.Mining_back.setStyleSheet("background-color:rgb(0, 255, 0);\n"
"color:rgb(255, 255, 255)")
        self.Mining_back.setObjectName("Mining_back")
        self.auto_cb = QtWidgets.QCheckBox(NowMining)
        self.auto_cb.setGeometry(QtCore.QRect(70, 510, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_cb.sizePolicy().hasHeightForWidth())
        self.auto_cb.setSizePolicy(sizePolicy)
        self.auto_cb.setStyleSheet("color:rgb(255, 255, 255)\n"
"")
        self.auto_cb.setObjectName("auto_cb")
        self.address_label = QtWidgets.QLabel(NowMining)
        self.address_label.setGeometry(QtCore.QRect(180, 190, 371, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_label.sizePolicy().hasHeightForWidth())
        self.address_label.setSizePolicy(sizePolicy)
        self.address_label.setStyleSheet("\n"
"color:rgb(255, 255, 255)\n"
"")
        self.address_label.setText("")
        self.address_label.setObjectName("address_label")
        self.filepath_label = QtWidgets.QLabel(NowMining)
        self.filepath_label.setGeometry(QtCore.QRect(70, 480, 461, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filepath_label.sizePolicy().hasHeightForWidth())
        self.filepath_label.setSizePolicy(sizePolicy)
        self.filepath_label.setText("")
        self.filepath_label.setObjectName("filepath_label")
        self.coinName_cb = QtWidgets.QLabel(NowMining)
        self.coinName_cb.setGeometry(QtCore.QRect(215, 528, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coinName_cb.sizePolicy().hasHeightForWidth())
        self.coinName_cb.setSizePolicy(sizePolicy)
        self.coinName_cb.setObjectName("coinName_cb")
        self.stop_pb = QtWidgets.QPushButton(NowMining)
        self.stop_pb.setGeometry(QtCore.QRect(60, 420, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_pb.sizePolicy().hasHeightForWidth())
        self.stop_pb.setSizePolicy(sizePolicy)
        self.stop_pb.setStyleSheet("background-color:rgb(0, 255, 0);\n"
"color:rgb(255, 255, 255)")
        self.stop_pb.setObjectName("stop_pb")
        self.hashrate_label = QtWidgets.QLabel(NowMining)
        self.hashrate_label.setGeometry(QtCore.QRect(320, 260, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hashrate_label.sizePolicy().hasHeightForWidth())
        self.hashrate_label.setSizePolicy(sizePolicy)
        self.hashrate_label.setStyleSheet("\n"
"color:rgb(255, 255, 255)\n"
"")
        self.hashrate_label.setObjectName("hashrate_label")
        self.startOver_pb = QtWidgets.QPushButton(NowMining)
        self.startOver_pb.setGeometry(QtCore.QRect(360, 420, 171, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startOver_pb.sizePolicy().hasHeightForWidth())
        self.startOver_pb.setSizePolicy(sizePolicy)
        self.startOver_pb.setStyleSheet("background-color:rgb(0, 255, 0);\n"
"color:rgb(255, 255, 255)")
        self.startOver_pb.setObjectName("startOver_pb")
        self.label_4 = QtWidgets.QLabel(NowMining)
        self.label_4.setGeometry(QtCore.QRect(60, 250, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(NowMining)
        self.label_3.setGeometry(QtCore.QRect(60, 180, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(NowMining)
        QtCore.QMetaObject.connectSlotsByName(NowMining)

    def retranslateUi(self, NowMining):
        _translate = QtCore.QCoreApplication.translate
        NowMining.setWindowTitle(_translate("NowMining", "Mr.Miner"))
        self.label.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">Mining</span></p></body></html>"))
        self.estCoin_label.setText(_translate("NowMining", "Sorry feature coming soon :("))
        self.label_5.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">Estimated Coin:</span></p></body></html>"))
        self.coinName_cb_2.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">next time Mr. Miner starts</span></p></body></html>"))
        self.Mining_back.setText(_translate("NowMining", "Settings"))
        self.auto_cb.setText(_translate("NowMining", "Automatically mine "))
        self.coinName_cb.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">Ethereum</span></p></body></html>"))
        self.stop_pb.setText(_translate("NowMining", "Stop Mining"))
        self.hashrate_label.setText(_translate("NowMining", "Sorry feature coming soon :("))
        self.startOver_pb.setText(_translate("NowMining", "Start Over"))
        self.label_4.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">Hash Rate:</span></p></body></html>"))
        self.label_3.setText(_translate("NowMining", "<html><head/><body><p><span style=\" color:#ffffff;\">Address:</span></p></body></html>"))

